export interface ApiResponse<T> { success: boolean; message?: string; data: T; errors?: Record<string, string[]>; timestamp: string }
export interface PageResponse<T> { content: T[]; page: number; size: number; totalElements: number; totalPages: number; hasNext: boolean }
export interface LoginRequest { username: string; password: string }
export interface RegisterRequest { username: string; password: string; email?: string; nickname?: string }
export interface AuthResponse { accessToken: string; refreshToken: string; expiresIn: number; userId: number; username: string; nickname: string }
export interface UserResponse { id: number; username: string; email?: string; nickname?: string; avatar?: string; createdAt: string }
export interface SpotResponse { id: number; name: string; category: string; description?: string; address?: string; latitude: number; longitude: number; popularity: number; avgRating: number; ratingCount?: number; imageUrl?: string; openingHours?: string; ticketPrice?: number; createdAt?: string }
export interface FoodResponse { id: number; name: string; cuisine?: string; restaurantName?: string; spotId?: number; description?: string; priceRange?: string; latitude?: number; longitude?: number; popularity: number; avgRating: number; ratingCount?: number; imageUrl?: string; createdAt?: string }
export interface DiaryResponse { id: string; userId: number; title: string; content: string; destination?: string; spotId?: number; images?: string[]; videoMeta?: { url: string; duration?: number; thumbnail?: string }; musicUrl?: string; popularity: number; avgRating: number; ratingCount?: number; isPublic?: boolean; createdAt: string; updatedAt?: string }
export interface RouteRequest { startLat: number; startLng: number; targets: { lat: number; lng: number; name?: string }[]; strategy?: string; transports?: string[]; finalDestinationIdx?: number }
export interface RouteResponse { path: { nodeId: string; latitude: number; longitude: number; name?: string; isTarget: boolean }[]; totalDistance: number; totalTime: number; visitOrder: string[] }
export interface SegmentInfo { fromNodeId: string; toNodeId: string; distance: number; time: number; roadName?: string; roadType?: string; transport?: string }