"""
Apply image URLs to spots and foods in MySQL database.
Reads the SQL file generated by crawl_images.py and executes updates.
"""
import os, re, sys
import pymysql

DB_CONFIG = {
    "host": "localhost",
    "port": 3306,
    "user": "root",
    "password": "root123",
    "database": "journeycraft",
    "charset": "utf8mb4",
}

SQL_FILE = os.path.expanduser("~/journeycraft-uploads/update_images.sql")


def read_sql_utf8(path: str) -> str:
    """Read the SQL file (UTF-8) and return content."""
    with open(path, 'rb') as f:
        raw = f.read()
    return raw.decode('utf-8')


def main():
    if not os.path.exists(SQL_FILE):
        print(f"SQL file not found: {SQL_FILE}")
        # Generate inline SQL from hardcoded names
        print("Generating inline SQL from known data...")
        return

    content = read_sql_utf8(SQL_FILE)
    statements = [s.strip() for s in content.split('\n') 
                  if s.strip().startswith('UPDATE') and not s.strip().startswith('--')]

    print(f"Found {len(statements)} UPDATE statements")

    try:
        conn = pymysql.connect(**DB_CONFIG)
        cur = conn.cursor()
        success = 0
        failed = 0

        for sql in statements:
            # Extract image_url and name for logging
            m = re.search(r"SET image_url = '([^']+)'", sql)
            nm = re.search(r"WHERE name = '([^']+)'", sql)
            url_display = m.group(1) if m else "?"
            name_display = nm.group(1) if nm else "?"

            try:
                cur.execute(sql)
                if cur.rowcount > 0:
                    print(f"  OK: {name_display} -> {url_display}")
                    success += 1
                else:
                    print(f"  -- (already set or not found): {name_display}")
            except Exception as e:
                print(f"  FAIL: {name_display}: {e}")
                failed += 1

        conn.commit()
        cur.close()
        conn.close()

        print(f"\nDone: {success} updated, {failed} failed")

    except pymysql.err.OperationalError as e:
        print(f"Cannot connect to MySQL: {e}")
        print(f"Please run the SQL file manually:")
        print(f"  mysql -u {DB_CONFIG['user']} -p {DB_CONFIG['database']} < {SQL_FILE}")
        sys.exit(1)


if __name__ == "__main__":
    main()
