import pymysql
c = pymysql.connect(host='localhost',port=3306,user='root',password='root123',database='journeycraft',charset='utf8mb4').cursor()
c.execute('SELECT COUNT(*) FROM users')
print('Users:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM spots')
print('Spots:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM facilities')
print('Facilities:', c.fetchone()[0])
c.execute('SELECT COUNT(DISTINCT category) FROM facilities')
print('Facility categories:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM foods')
print('Foods:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM road_edges')
print('Road edges:', c.fetchone()[0])
